#ifndef HEADERS_FUNCTIONS_OVERLAY00_H_
#define HEADERS_FUNCTIONS_OVERLAY00_H_
undefined GetStylerLevel(void);
bool GetPartner1Status(void);
void SetPartner1Status(bool param_1);
bool GetPartner2Status(void);
void SetPartner2Status(bool param_1);
bool GetPartner3Status(void);
void SetPartner3Status(bool param_1);
bool GetPartner4Status(void);
void SetPartner4Status(bool param_1);
bool GetPartner5Status(void);
void SetPartner5Status(bool param_1);
bool GetPartner6Status(void);
void SetPartner6Status(bool param_1);
bool GetPartner7Status(void);
void SetPartner7Status(bool param_1);
bool GetPartner8Status(void);
void SetPartner8Status(bool param_1);
bool GetPartner9Status(void);
void SetPartner9Status(bool param_1);
bool GetPartner10Status(void);
void SetPartner10Status(bool param_1);
bool GetPartner11Status(void);
void SetPartner11Status(bool param_1);
bool GetPartner12Status(void);
void SetPartner12Status(bool param_1);
bool GetPartner13Status(void);
void SetPartner13Status(bool param_1);
bool GetPartner14Status(void);
void SetPartner14Status(bool param_1);
bool GetPartner15Status(void);
void SetPartner15Status(bool param_1);
bool GetPartner16Status(void);
void SetPartner16Status(bool param_1);
bool GetPartner17Status(void);
void SetPartner17Status(bool param_1);
int8_t GetActiveQuestId(void);
int8_t GetActiveMissionId(void);
void DebugPrintAllScriptVars(void);
int64_t GetCaptureLineLenRecordSimple(void);
void SetCaptureLineLenRecordSimple(int32_t param_1);
int32_t GetNumLoopsRecordSimple(void);
void SetNumLoopsRecordSimple(undefined4 param_1);
int16_t GetPokemonCapturedRecordSimple(void);
void SetPokemonCapturedRecordSimple(undefined2 param_1);
int16_t GetPokemonFledRecordSimple(void);
void SetPokemonFledRecordSimple(undefined2 param_1);
int16_t GetPokeAssistsUsedRecordSimple(void);
void SetPokeAssistsUsedSimple(undefined2 param_1);
int32_t GetMaxPlayTimeSeconds(void);
#endif